export const books = [
    { id: 1, title: 'Kebun Sawitku', author: 'monokotil', year: 2025 },
    { id: 2, title: 'Misteri Tembok Ratapan Solo', author: 'Pria Gorong-Gorong', year: 2024 },
    { id: 3, title: 'Misteri Server PDN Lupa Password', author: 'Admin Magang', year: 2024 },
    { id: 4, title: 'Seni Menghilang Saat Dicari KPK', author: 'Harun M.', year: 2026 },
    { id: 5, title: 'Anggaran Gorden 20 Milyar', author: 'Sekjen Hebat', year: 2022 },
    { id: 6, title: 'Lapor Mas Wapres: Curhatan Rakyat', author: 'Gibran F.', year: 2024 },
    { id: 7, title: 'Fufufafa: Jejak Digital yang Abadi', author: 'Anonim Kaskus', year: 2024 },
    { id: 8, title: 'Dinasti Bukan Sekadar Nama Roti', author: 'Paman Konstitusi', year: 2023 },
    { id: 9, title: 'Jalan Rusak Langsung Mulus Pas RI 1 Datang', author: 'Kontraktor Dadakan', year: 2025 },
    { id: 10, title: 'Strategi Menang Pilkada Jalur MK', author: 'Bocah Kosong', year: 2024 },
    { id: 11, title: 'Koleksi Pantun Penenang Demo', author: 'Buzzer Politik', year: 2026 },
    { id: 12, title: 'Makan Siang Gratis vs Susu UHT', author: 'Tim Ahli Gizi Politik', year: 2025 },
    { id: 13, title: 'Tutorial Menjadi Intel Berkedok Tukang Bakso', author: 'Bang Napi', year: 2023 },
    { id: 14, title: 'Bansos: Cinta yang Terbagi di Kotak Suara', author: 'Menteri Sosial', year: 2024 },
    { id: 15, title: 'Raja Jawa: Mitos atau Realitas?', author: 'Bahlil L.', year: 2024 },
    { id: 16, title: 'Kamus Bahasa Jaksel Untuk Diplomat', author: 'Anak Jaksel', year: 2025 },
    { id: 17, title: 'Cara Jawab "Saya Tidak Tahu" Saat Sidang', author: 'Saksi Kunci', year: 2026 },
    { id: 18, title: 'Main Slot Sambil Rapat Paripurna', author: 'Anggota Terhormat', year: 2023 },
    { id: 19, title: 'Revisi UU Secepat Kilat', author: 'Baleg DPR', year: 2024 },
    { id: 20, title: 'Si Paling Anti-Kritik', author: 'Pejabat Baper', year: 2025 }
];